# Generated by Django 4.2 on 2024-07-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('url_pattern', models.CharField(max_length=255)),
                ('page_type', models.CharField(max_length=50)),
                ('title_css', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
