# Generated by Django 4.2 on 2024-07-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservice',
            name='list_attribute',
            field=models.CharField(default='li', max_length=255),
        ),
    ]
