# Generated by Django 4.2 on 2024-07-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemServices', '0002_systemservice_list_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservice',
            name='list_attribute_value',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
