# Generated by Django 4.2 on 2024-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemServices', '0003_systemservice_list_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservice',
            name='item_title_query_selector',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
