# Generated by Django 4.2 on 2024-07-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemServices', '0004_systemservice_item_title_query_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservice',
            name='list_css',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemservice',
            name='list_selector_type',
            field=models.CharField(default='ATTRIBUTE', max_length=255),
        ),
    ]
