# Generated by Django 4.2 on 2024-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemServices', '0006_systemservice_items_to_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservice',
            name='item_identification_id',
            field=models.CharField(default='id', max_length=255),
        ),
    ]
