# Generated by Django 4.2 on 2024-07-09 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategoryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('clicks', models.IntegerField()),
                ('searches', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customercategory')),
            ],
        ),
    ]
